#%RAML 1.0
title: Missing content type in method responses
version: 1.0
/foo:
  get:
    responses:
      200:
        body:
          'application/vnd.representation1+json':
            type:
              properties:
                foo1: string
          'application/vnd.representation2+json':
            type:
              properties:
                foo1: number
